services:
  - type: web
    name: stock-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.18
      - key: DATABASE_URL
        sync: false
