nifty_500_symbols = ["360ONE.NS","3MINDIA.NS","ABB.NS","ACC.NS","AIAENG.NS","APLAPOLLO.NS","AUBANK.NS","AADHARHFC.NS","AARTIIND.NS","AAVAS.NS","ABBOTINDIA.NS","ACE.NS","ADANIENSOL.NS","ADANIENT.NS","ADANIGREEN.NS","ADANIPORTS.NS","ADANIPOWER.NS","ATGL.NS","AWL.NS","ABCAPITAL.NS","ABFRL.NS","ABREL.NS","ABSLAMC.NS","AEGISLOG.NS","AFFLE.NS","AJANTPHARM.NS","AKUMS.NS","APLLTD.NS","ALKEM.NS","ALKYLAMINE.NS","ALOKINDS.NS","ARE&M.NS","AMBER.NS","AMBUJACEM.NS","ANANDRATHI.NS","ANANTRAJ.NS","ANGELONE.NS","APARINDS.NS","APOLLOHOSP.NS","APOLLOTYRE.NS","APTUS.NS","ACI.NS","ASAHIINDIA.NS","ASHOKLEY.NS","ASIANPAINT.NS","ASTERDM.NS","ASTRAZEN.NS","ASTRAL.NS","ATUL.NS","AUROPHARMA.NS","AVANTIFEED.NS","DMART.NS","AXISBANK.NS","BASF.NS","BEML.NS","BLS.NS","BSE.NS","BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BAJAJHLDNG.NS","BALAMINES.NS","BALKRISIND.NS","BALRAMCHIN.NS","BANDHANBNK.NS","BANKBARODA.NS","BANKINDIA.NS","MAHABANK.NS","BATAINDIA.NS","BAYERCROP.NS","BERGEPAINT.NS","BDL.NS","BEL.NS","BHARATFORG.NS","BHEL.NS","BPCL.NS","BHARTIARTL.NS","BHARTIHEXA.NS","BIKAJI.NS","BIOCON.NS","BIRLACORPN.NS","BSOFT.NS","BLUEDART.NS","BLUESTARCO.NS","BBTC.NS","BOSCHLTD.NS","BRIGADE.NS","BRITANNIA.NS","MAPMYINDIA.NS","CCL.NS","CESC.NS","CGPOWER.NS","CIEINDIA.NS","CRISIL.NS","CAMPUS.NS","CANFINHOME.NS","CANBK.NS","CAPLIPOINT.NS","CGCL.NS","CARBORUNIV.NS","CASTROLIND.NS","CEATLTD.NS","CELLO.NS","CENTRALBK.NS","CDSL.NS","CENTURYPLY.NS","CERA.NS","CHALET.NS","CHAMBLFERT.NS","CHEMPLASTS.NS","CHENNPETRO.NS","CHOLAHLDNG.NS","CHOLAFIN.NS","CIPLA.NS","CUB.NS","CLEAN.NS","COALINDIA.NS","COCHINSHIP.NS","COFORGE.NS","COLPAL.NS","CAMS.NS","CONCORDBIO.NS","CONCOR.NS","COROMANDEL.NS","CRAFTSMAN.NS","CREDITACC.NS","CROMPTON.NS","CUMMINSIND.NS","CYIENT.NS","DLF.NS","DOMS.NS","DABUR.NS","DALBHARAT.NS","DATAPATTNS.NS","DEEPAKFERT.NS","DEEPAKNTR.NS","DELHIVERY.NS","DEVYANI.NS","DIVISLAB.NS","DIXON.NS","LALPATHLAB.NS","DRREDDY.NS","EIDPARRY.NS","EIHOTEL.NS","EASEMYTRIP.NS","EICHERMOT.NS","ELECON.NS","ELGIEQUIP.NS","EMAMILTD.NS","EMCURE.NS","ENDURANCE.NS","ENGINERSIN.NS","EQUITASBNK.NS","ERIS.NS","ESCORTS.NS","EXIDEIND.NS","NYKAA.NS","FEDERALBNK.NS","FACT.NS","FINEORG.NS","FINCABLES.NS","FINPIPE.NS","FSL.NS","FIVESTAR.NS","FORTIS.NS","GRINFRA.NS","GAIL.NS","GVT&D.NS","GMRAIRPORT.NS","GRSE.NS","GICRE.NS","GILLETTE.NS","GLAND.NS","GLAXO.NS","GLENMARK.NS","MEDANTA.NS","GODIGIT.NS","GPIL.NS","GODFRYPHLP.NS","GODREJAGRO.NS","GODREJCP.NS","GODREJIND.NS","GODREJPROP.NS","GRANULES.NS","GRAPHITE.NS","GRASIM.NS","GESHIP.NS","GRINDWELL.NS","GAEL.NS","FLUOROCHEM.NS","GUJGASLTD.NS","GMDCLTD.NS","GNFC.NS","GPPL.NS","GSFC.NS","GSPL.NS","HEG.NS","HBLENGINE.NS","HCLTECH.NS","HDFCAMC.NS","HDFCBANK.NS","HDFCLIFE.NS","HFCL.NS","HAPPSTMNDS.NS","HAVELLS.NS","HEROMOTOCO.NS","HSCL.NS","HINDALCO.NS","HAL.NS","HINDCOPPER.NS","HINDPETRO.NS","HINDUNILVR.NS","HINDZINC.NS","POWERINDIA.NS","HOMEFIRST.NS","HONASA.NS","HONAUT.NS","HUDCO.NS","ICICIBANK.NS","ICICIGI.NS","ICICIPRULI.NS","ISEC.NS","IDBI.NS","IDFCFIRSTB.NS","IFCI.NS","IIFL.NS","INOXINDIA.NS","IRB.NS","IRCON.NS","ITCHOTELS.NS","ITC.NS","ITI.NS","INDGN.NS","INDIACEM.NS","INDIAMART.NS","INDIANB.NS","IEX.NS","INDHOTEL.NS","IOC.NS","IOB.NS","IRCTC.NS","IRFC.NS","IREDA.NS","IGL.NS","INDUSTOWER.NS","INDUSINDBK.NS","NAUKRI.NS","INFY.NS","INOXWIND.NS","INTELLECT.NS","INDIGO.NS","IPCALAB.NS","JBCHEPHARM.NS","JKCEMENT.NS","JBMA.NS","JKLAKSHMI.NS","JKTYRE.NS","JMFINANCIL.NS","JSWENERGY.NS","JSWINFRA.NS","JSWSTEEL.NS","JPPOWER.NS","J&KBANK.NS","JINDALSAW.NS","JSL.NS","JINDALSTEL.NS","JIOFIN.NS","JUBLFOOD.NS","JUBLINGREA.NS","JUBLPHARMA.NS","JWL.NS","JUSTDIAL.NS","JYOTHYLAB.NS","JYOTICNC.NS","KPRMILL.NS","KEI.NS","KNRCON.NS","KPITTECH.NS","KSB.NS","KAJARIACER.NS","KPIL.NS","KALYANKJIL.NS","KANSAINER.NS","KARURVYSYA.NS","KAYNES.NS","KEC.NS","KFINTECH.NS","KIRLOSBROS.NS","KIRLOSENG.NS","KOTAKBANK.NS","KIMS.NS","LTF.NS","LTTS.NS","LICHSGFIN.NS","LTIM.NS","LT.NS","LATENTVIEW.NS","LAURUSLABS.NS","LEMONTREE.NS","LICI.NS","LINDEINDIA.NS","LLOYDSME.NS","LUPIN.NS","MMTC.NS","MRF.NS","LODHA.NS","MGL.NS","MAHSEAMLES.NS","M&MFIN.NS","M&M.NS","MAHLIFE.NS","MANAPPURAM.NS","MRPL.NS","MANKIND.NS","MARICO.NS","MARUTI.NS","MASTEK.NS","MFSL.NS","MAXHEALTH.NS","MAZDOCK.NS","METROBRAND.NS","METROPOLIS.NS","MINDACORP.NS","MSUMI.NS","MOTILALOFS.NS","MPHASIS.NS","MCX.NS","MUTHOOTFIN.NS","NATCOPHARM.NS","NBCC.NS","NCC.NS","NHPC.NS","NLCINDIA.NS","NMDC.NS","NSLNISP.NS","NTPC.NS","NH.NS","NATIONALUM.NS","NAVINFLUOR.NS","NESTLEIND.NS","NETWEB.NS","NETWORK18.NS","NEWGEN.NS","NAM-INDIA.NS","NUVAMA.NS","NUVOCO.NS","OBEROIRLTY.NS","ONGC.NS","OIL.NS","OLECTRA.NS","PAYTM.NS","OFSS.NS","POLICYBZR.NS","PCBL.NS","PIIND.NS","PNBHOUSING.NS","PNCINFRA.NS","PTCIL.NS","PVRINOX.NS","PAGEIND.NS","PATANJALI.NS","PERSISTENT.NS","PETRONET.NS","PFIZER.NS","PHOENIXLTD.NS","PIDILITIND.NS","PEL.NS","PPLPHARMA.NS","POLYMED.NS","POLYCAB.NS","POONAWALLA.NS","PFC.NS","POWERGRID.NS","PRAJIND.NS","PRESTIGE.NS","PGHH.NS","PNB.NS","QUESS.NS","RRKABEL.NS","RBLBANK.NS","RECLTD.NS","RHIM.NS","RITES.NS","RADICO.NS","RVNL.NS","RAILTEL.NS","RAINBOW.NS","RAJESHEXPO.NS","RKFORGE.NS","RCF.NS","RATNAMANI.NS","RTNINDIA.NS","RAYMOND.NS","REDINGTON.NS","RELIANCE.NS","ROUTE.NS","SBFC.NS","SBICARD.NS","SBILIFE.NS","SJVN.NS","SKFINDIA.NS","SRF.NS","SAMMAANCAP.NS","MOTHERSON.NS","SANOFI.NS","SAPPHIRE.NS","SAREGAMA.NS","SCHAEFFLER.NS","SCHNEIDER.NS","SCI.NS","SHREECEM.NS","RENUKA.NS","SHRIRAMFIN.NS","SHYAMMETL.NS","SIEMENS.NS","SIGNATURE.NS","SOBHA.NS","SOLARINDS.NS","SONACOMS.NS","SONATSOFTW.NS","STARHEALTH.NS","SBIN.NS","SAIL.NS","SWSOLAR.NS","SUMICHEM.NS","SPARC.NS","SUNPHARMA.NS","SUNTV.NS","SUNDARMFIN.NS","SUNDRMFAST.NS","SUPREMEIND.NS","SUVENPHAR.NS","SUZLON.NS","SWANENERGY.NS","SYNGENE.NS","SYRMA.NS","TBOTEK.NS","TVSMOTOR.NS","TVSSCS.NS","TANLA.NS","TATACHEM.NS","TATACOMM.NS","TCS.NS","TATACONSUM.NS","TATAELXSI.NS","TATAINVEST.NS","TATAMOTORS.NS","TATAPOWER.NS","TATASTEEL.NS","TATATECH.NS","TTML.NS","TECHM.NS","TECHNOE.NS","TEJASNET.NS","NIACL.NS","RAMCOCEM.NS","THERMAX.NS","TIMKEN.NS","TITAGARH.NS","TITAN.NS","TORNTPHARM.NS","TORNTPOWER.NS","TRENT.NS","TRIDENT.NS","TRIVENI.NS","TRITURBINE.NS","TIINDIA.NS","UCOBANK.NS","UNOMINDA.NS","UPL.NS","UTIAMC.NS","UJJIVANSFB.NS","ULTRACEMCO.NS","UNIONBANK.NS","UBL.NS","UNITDSPR.NS","USHAMART.NS","VGUARD.NS","VIPIND.NS","DBREALTY.NS","VTL.NS","VARROC.NS","VBL.NS","MANYAVAR.NS","VEDL.NS","VIJAYA.NS","VINATIORGA.NS","IDEA.NS","VOLTAS.NS","WELCORP.NS","WELSPUNLIV.NS","WESTLIFE.NS","WHIRLPOOL.NS","WIPRO.NS","YESBANK.NS","ZFCVINDIA.NS","ZEEL.NS","ZENSARTECH.NS","ETERNAL.NS","ZYDUSLIFE.NS","ECLERX.NS"]

sectors = [
    "Information Technology (IT)",
    "Banking & Financial Services (BFSI)",
    "Pharmaceuticals & Healthcare",
    "Automobiles",
    "Oil & Gas",
    "Fast-Moving Consumer Goods (FMCG)",
    "Metals & Mining",
    "Power & Utilities",
    "Telecom",
    "Real Estate & Construction",
    "Infrastructure",
    "Chemicals & Specialty Chemicals",
    "Consumer Durables",
    "Textiles",
    "Cement & Building Materials",
    "Logistics",
    "Media & Entertainment",
    "Hospitality & Tourism",
    "Renewable Energy",
    "Electric Vehicles (EVs)",
    "Agriculture & Agrochemicals",
    "Aviation",
    "Defence & Aerospace",
    "Sugar & Fertilizers",
    "Capital Goods"
]

nifty_next_500_symbols = [
    # Only working symbols remain
    "MANGCHEFER.NS", "PARADEEP.NS", "DRREDDY.NS", "ZENTEC.NS", "KITEX.NS", "INDIAGLYCO.NS", "COFFEEDAY.BO", "CENTUM.BO", "UTTAMSUGAR.BO", "PRIVISCL.BO", "FORCEMOT.NS", "SPORTKING.BO", "NUCLEUS.BO", "JINDALPHOT.BO", "ANURAS.BO", "AXISCADES.NS", "PARAGMILK.BO", "YUKEN.BO", "SANGHVIMOV.BO", "SSWL.BO", "TITAN.NS", "CUPID.BO", "SINDHUTRAD.BO", "WINDMACHIN.BO", "TDPOWERSYS.BO", "KOLTEPATIL.BO", "KILITCH.BO", "KRYSTAL.BO", "VESUVIUS.NS", "SURYAROSNI.BO", "THYROCARE.NS", "KRBL.NS", "UFLEX.NS", "GABRIEL.NS", "YATRA.NS", "APOLLO.NS", "EIMCOELECO.BO", "RPTECH.BO", "KHAITANLTD.BO", "DCBBANK.BO", "REPRO.BO", "ISGEC.NS", "DHANUKA.NS", "MOIL.NS", "RELINFRA.NS", "FIEMIND.NS", "SUBROS.NS", "AMBIKCO.BO", "LTFOODS.NS", "MARKSANS.NS", "WABAG.NS", "TEAMLEASE.NS", "RUPA.NS", "DPWIRES.BO", "MALUPAPER.BO", "RSYSTEMS.BO", "SATIA.BO", "SVPGLOB.BO", "BPL.BO", "MARALOVER.BO", "KRISHIVAL.BO", "TRACXN.NS", "EDELWEISS.NS", "UDS.BO", "AMIORG.BO", "MAHLIFE.NS", "LGBBROSLTD.BO", "SRESTHA.BO", "KOTHARIPRO.BO", "FOODSIN.BO", "VAIBHAVGBL.BO", "GOCOLORS.NS", "SAFARI.NS", "PAVNAIND.BO", "MEDIASSIST.NS", "DREAMFOLKS.NS", "GREENLAM.NS", "HTMEDIA.NS", "ANMOL.BO", "MPSLTD.NS", "DELTAMAGNT.BO", "BHANDARI.BO", "GUFICBIO.BO", "SADBHIN.BO", "A2ZINFRA.BO", "GAYAHWS.BO", "JAYAGROGN.BO", "NAGREEKCAP.BO", "VISHNU.BO", "TAKE.BO", "SUBEXLTD.BO", "THOMASCOTT.BO", "HILTON.BO", "WEWIN.BO", "SHREEPUSHK.BO", "REFEX.BO", "INVENTURE.BO", "SHAREINDIA.BO", "TIJARIA.BO", "VAKRANGEE.BO", "SMLISUZU.NS",
]

nifty_50_symbols = [
    "ABB.NS", "ACC.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "AMBUJACEM.NS",
    "ASIANPAINT.NS", "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "BAJFINANCE.NS",
    "BANDHANBNK.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BHARTIARTL.NS", "BIOCON.NS",
    "BPCL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "COLPAL.NS",
    "CONCOR.NS", "DABUR.NS", "DIVISLAB.NS", "DLF.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GAIL.NS", "GLAND.NS", "GLENMARK.NS", "GMRINFRA.NS",
    "GODREJCP.NS", "GRASIM.NS", "HAVELLS.NS", "HEROMOTOCO.NS", "HINDALCO.NS",
    "HINDPETRO.NS", "HINDUNILVR.NS", "HDFCBANK.NS", "HDFCLIFE.NS",
    "ICICIBANK.NS", "ICICIPRULI.NS", "INDHOTEL.NS", "INDIGO.NS", "INDUSINDBK.NS",
    "INFY.NS", "IOC.NS", "ITC.NS", "JSWSTEEL.NS", "JUBLFOOD.NS",
    "KOTAKBANK.NS", "LT.NS", "LUPIN.NS", "M&M.NS", "MARICO.NS",
    "MARUTI.NS", "MFSL.NS", "NAUKRI.NS", "NAVINFLUOR.NS",
    "NESTLEIND.NS", "NMDC.NS", "ONGC.NS", "PIIND.NS", "PIDILITIND.NS",
    "PNB.NS", "POWERGRID.NS", "RELIANCE.NS", "SBICARD.NS", "SBILIFE.NS",
    "SBIN.NS", "SHREECEM.NS", "SIEMENS.NS", "SRF.NS", "SUNPHARMA.NS",
    "TATACONSUM.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "TCS.NS", "TECHM.NS",
    "TITAN.NS", "TORNTPHARM.NS", "ULTRACEMCO.NS", "UPL.NS", "VEDL.NS",
    "WIPRO.NS", "ZEEL.NS"
]


nifty_5_symbols = [
    "ASIANPAINT.NS", "BAJFINANCE.NS", "BRITANNIA.NS", "CIPLA.NS",
    "EICHERMOT.NS",  "HDFCBANK.NS", "INDHOTEL.NS", "INDIGO.NS", "RELIANCE.NS", 
    "TITAN.NS", "WIPRO.NS", "ZEEL.NS"
]

sector_mapping = {
    "Information Technology (IT)": ["HCL", "INFY", "TCS", "TECHM", "WIPRO", "LTIM", "OFSS", "COFORGE",
                                   "PERSISTENT", "ZENSAR", "ECLERX", "INTELLECT", "BSOFT", "CAMS", "CYIENT"],
    "Banking & Financial Services (BFSI)": ["BANK", "HDFC", "ICICI", "SBI", "KOTAK", "AXIS", "INDUSINDBK",
                                           "BANDHAN", "FEDERAL", "IDFC", "AUBANK", "BAJAJFINSV", "BAJFINANCE",
                                           "CHOLA", "SBICARD", "MUTHOOT", "MANAPPURAM", "ABBOT", "ABSLAMC",
                                           "HDFCAMC", "UTIAMC", "M&MFIN", "MOTILALOFS", "IIFL", "JMFINANCIL"],
    "Pharmaceuticals & Healthcare": ["DRREDDY", "SUNPHARMA", "CIPLA", "LUPIN", "AUROPHARMA", "DIVISLAB",
                                    "BIOCON", "GLAND", "GLENMARK", "IPCALAB", "ALKEM", "TORNTPHARM",
                                    "AJANTPHARM", "LALPATHLAB", "FORTIS", "MEDANTA", "MAXHEALTH", "KIMS"],
    "Automobiles": ["M&M", "MARUTI", "TATAMOTORS", "EICHERMOT", "BAJAJ-AUTO", "HEROMOTOCO", "TVSMOTOR",
                   "ASHOKLEY", "BHARATFORG", "BALKRISIND", "SONACOMS", "JKTYRE", "AMARAJA", "SMLISUZU"],
    "Oil & Gas": ["ONGC", "IOC", "BPCL", "HPCL", "GAIL", "PETRONET", "GUJGAS", "AEGISLOG", "ADANIGAS"],
    "Fast-Moving Consumer Goods (FMCG)": ["HINDUNILVR", "ITC", "NESTLE", "BRITANNIA", "DABUR", "GODREJCP",
                                         "MARICO", "COLPAL", "EMAMILTD", "RADICO", "VBL", "BATAINDIA",
                                         "VGUARD", "WHIRLPOOL", "CROMPTON", "BLUESTAR", "HAVELLS", "VIPIND"],
    "Metals & Mining": ["HINDALCO", "VEDL", "JSWSTEEL", "TATASTEEL", "NMDC", "NATIONALUM", "HINDZINC",
                       "SAIL", "APLAPOLLO", "RATNAMANI", "JINDALSTEL", "MAHSEAMLES"],
    "Power & Utilities": ["NTPC", "POWERGRID", "TATAPOWER", "NHPC", "TORNTPOWER", "JSWENERGY", "ADANIPOWER",
                         "CESC", "SJVN", "IREDA", "JPPOWER"],
    "Telecom": ["BHARTIARTL", "IDEA"],
    "Real Estate & Construction": ["DLF", "GODREJPROP", "OBEROIRLTY", "LODHA", "BRIGADE", "PRESTIGE", "SOBHA",
                                  "MAHLIFE", "PURVA", "DBREALTY"],
    "Infrastructure": ["L&T", "ADANIPORTS", "GMR", "IRB", "IRCON", "RVNL", "NCC", "GRINFRA", "PNCINFRA",
                      "HSCL", "KPIL", "KEC", "KNRCON"],
    "Chemicals & Specialty Chemicals": ["SRF", "PIDILITIND", "ATUL", "ALKEM", "FINEORG", "NAVINFLUOR",
                                       "FLUOROCHEM", "ANUP", "GNFC", "GSFC"],
    "Consumer Durables": ["CROMPTON", "HAVELLS", "BLUESTAR", "AMBER", "BAJAJELEC", "WHIRLPOOL", "VGUARD"],
    "Cement & Building Materials": ["ULTRACEMCO", "ACC", "AMBUJACEM", "SHREECEM", "JKCEMENT", "RAMCOCEM",
                                   "CENTURYPLY", "KALYANKJIL"],
    "Logistics": ["DELHIVERY", "BLUEDART", "CONCOR", "TCI", "VTL"],
    "Media & Entertainment": ["ZEEL", "SUNTV", "DISHTV", "INOXLEIS", "PVRINOX"],
    "Renewable Energy": ["ADANIGREEN", "WEBELSOLAR", "SWSOLAR", "INOXWIND"],
    "Defence & Aerospace": ["HAL", "BEL", "BDL", "GRSE", "DATAPATTNS", "MAZDOCK"],
    "Agriculture & Agrochemicals": ["UPL", "RALLIS", "DEEPAKFERT", "PIIND", "COROMANDEL", "CHAMBAL"],
    "Capital Goods": ["SIEMENS", "ABB", "BHEL", "THERMAX", "ELGIEQUIP", "KSB", "CGCL", "CUMMINSIND"],
    "others": ["3M", "AIAENG", "AAVAS", "AARTIIND", "360ONE"]  # Generic category
}

def fetch_nifty500_list():
    return nifty_500_symbols

def fetch_nifty_list_all():
    return nifty_500_symbols+nifty_next_500_symbols


def fetch_nifty50_list():
    return nifty_50_symbols

def fetch_nifty5_list():
    return nifty_5_symbols