name: Daily Stock Data Sync

on:
  schedule:
    # Run every day at 6:00 PM IST (12:30 PM UTC)
    - cron: '30 12 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run daily sync
      env:
        ACTIVE_DATABASE: prod
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python scripts/daily_ohlcv_syncer.py
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Daily sync failed. Please check the logs.'
          })
